platform:ios, '12.0'
use_frameworks!


target 'VideoLab_Example' do
  pod 'MTTransitions', :path => '/Users/joey/MTTransitions'
  pod 'VideoLab', :path => '../'

  target 'VideoLab_Tests' do
    inherit! :search_paths

    
  end
end
